### PR TITLE
Fixed interpolation method

### PR DESCRIPTION
**Pull request by AzazKamaz**
Changed LINEAR interpolation method to AVERAGE.
Linear interpolation gives a very poor result when scaling big images

### CODE REVIEW

**Comment by AzazKamaz** [comment]
Of curse: https://imgur.com/a/IpkXs8N

**Comment by MarkOSullivan94** [comment]
Will test this out tomorrow and check what kind of results I have and post the results too, if it seems to be better, I'll merge it in.

**Comment by AzazKamaz** [comment]
Ok, if no, I will create parameter in config, because I need this feature for my app))

**Comment by MarkOSullivan94** [comment]
@AzazKamaz did some testing this morning and here is an album with my results: https://imgur.com/a/Uf19ACC

**Comment by AzazKamaz** [comment]
@MarkOSullivan94 one problem is "new-ios-1024x1024@1x", maybe it caused by small resolution of original icon, i will test it and add this case to code

**Comment by AzazKamaz** [comment]
@MarkOSullivan94 fixed this case

**Comment by MarkOSullivan94** [comment]
I'm not sure if was a problem with "new-ios-1024x1024@1x" it looks fine here: https://imgur.com/XDNixsI

Looks like it's a big improvement on original version: https://imgur.com/WpfHjsg

**Comment by MarkOSullivan94** [comment]
@franzsilva want to test these changes out?

**Comment by MarkOSullivan94** [comment]
@AzazKamaz to help with testing this, I've added an example project with 3 example icon images which can be used to generate the icons. It can be found here: https://github.com/franzsilva/flutter_launcher_icons/tree/master/example

**Comment by MarkOSullivan94** [comment]
After doing some testing with two of the example icons (128x128 & 710x599) I'm definitely seeing an improvement in the quality of the smaller icons. Not sure about the larger icons.

Many thanks for making these improvements and making a PR @AzazKamaz!

**Pull request merged**
